routes/backend.php
<?php


Route::get('test/update_account_balance', '\App\Http\Controllers\Test@updateAccountBalance');
//
Route::get('login', 'Backend\Login@index');

Route::post('login', 'Backend\Login@login');
Route::get('logout', 'Backend\Login@logout');

Route::group(['middleware' => 'auth.backend'], function () {

    Route::post('/image/editor-upload', 'Backend\Image@editorUpload');

    Route::get('', 'Backend\Home@index');
    Route::get('home', 'Backend\Home@index');
    Route::resource('admin', 'Backend\Admin');
    Route::resource('post_category', 'Backend\PostCategory');

    Route::post('order/change_status', 'Backend\Order@changeStatus');
    Route::get('order/delete', 'Backend\Order@delete');
    Route::get('order', 'Backend\Order@index');

    #bài viết
    Route::post('/image/editor-upload', 'Backend\Image@editorUpload');
    Route::get('post/delete/{id}', 'Backend\Post@delete');
    Route::resource('post', 'Backend\Post');

    #video
    Route::get('video/delete/{id}', 'Backend\Video@delete');
    Route::resource('video', 'Backend\Video');

    #danh mục sản phẩm
    Route::get('product_category/delete/{id}', 'Backend\ProductCategory@delete');
    Route::resource('product_category', 'Backend\ProductCategory');

    #thương hiệu sản phẩm
    Route::get('product_brand/delete/{id}', 'Backend\ProductBrand@delete');
    Route::resource('product_brand', 'Backend\ProductBrand');


	Route::get('product_price/list', 'Backend\ProductPrice@lists');
	Route::post('product_price/add', 'Backend\ProductPrice@add');
	Route::post('product_price/remove', 'Backend\ProductPrice@remove');

	Route::get('product_promotion/list', 'Backend\ProductPromotion@lists');
	Route::post('product_promotion/add', 'Backend\ProductPromotion@add');
	Route::post('product_promotion/remove', 'Backend\ProductPromotion@remove');

    Route::post('product_it/add', 'Backend\ProductIt@add');
    
    Route::post('product_image/add', 'Backend\ProductImage@add');
    Route::post('product_image/remove', 'Backend\ProductImage@remove');
    Route::get('product_image/lists', 'Backend\ProductImage@lists');


    Route::get('product/delete/{id}', 'Backend\Product@delete');
    Route::resource('product', 'Backend\Product');
    
    Route::get('banner/delete/{id}', 'Backend\Banner@delete');
    Route::resource('banner', 'Backend\Banner');

	Route::get('banner_sub/delete/{id}', 'Backend\BannerSub@delete');
    Route::resource('banner_sub', 'Backend\BannerSub');
	
    Route::resource('system_config', 'Backend\SystemConfig');

	Route::get('partner/delete/{id}', 'Backend\Partner@delete');
	Route::resource('partner', 'Backend\Partner');
});

routes/frontend.php
<?php
//Route::get('/test', '\App\Http\Controllers\Frontend\Test@index');
Route::get('/', '\App\Http\Controllers\Frontend\Home@index');
Route::get('/san-pham/{slug}.html', '\App\Http\Controllers\Frontend\Product@detail');

//Route::get('/gioi-thieu', 'Frontend\Post@show');
//Route::get('/lien-he', 'Frontend\Post@show');

Route::get('/bai-viet/{slug}/{id}.html', '\App\Http\Controllers\Frontend\Post@show');



Route::get('/danh-muc/{slug}', 'Frontend\Post@index');
Route::get('/tim-kiem', 'Frontend\Product@search');
Route::post('/order/create', 'Frontend\Order@create');


$parents = \App\Models\ProductCategory::query()->where('parent_id',0)->get();
$parents_slugs = [];
if(isset($parents) && !empty($parents)) {
	foreach($parents as $parent) {
		$parents_slugs[] = $parent->slug;
	}
}
Route::get('/{category_slug}/{p1?}/{p2?}',
    '\App\Http\Controllers\Frontend\Product@index')
    ->where(['category_slug' => implode('|',$parents_slugs)]);

routes/web.php
<?php

require_once 'frontend.php';
Route::group(['prefix' => 'backend'], function () {
    require_once 'backend.php';
});

app/Models/BannerSub.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BannerSub extends Model
{

    /**
     * @var string
     */
    protected $table = 'banner_sub';
    protected $guarded = [];
    /**
     * @var bool
     */
    public $timestamps = true;

    const CREATED_AT = 'created_time';
    const UPDATED_AT = 'updated_time';



}

app/Http/Controllers/Backend/Admin.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;

class Admin extends Base
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $breadcrumb = [
            'title' => 'Danh sách quản trị',
            'items' => [

            ]
        ];

        $users = \App\Models\Admin::query()->orderBy('created_time', 'desc')->paginate(24);

        return view('backend.admin.index', compact('users', 'breadcrumb'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $breadcrumb = [
            'title' => 'Thêm quản trị',
            'items' => [
                [
                    'title' => 'Danh sách quản trị',
                    'url' => '/backend/admin'
                ],
                [
                    'title' => 'Thêm quản trị'
                ]
            ]
        ];

        return view('backend.admin.create', compact(
            'breadcrumb'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $__request = $request->all();

        $user = new \App\Models\Admin();

        $user->username = $__request["username"];
        $user->password = md5($__request["password"]);

        $user->status = isset($__request["status"]) ? 1 : 0;

        $insert = $user->save();

        if ($insert) {
            return redirect('backend/user')->with('success', 'Thêm Danh mục thành công');
        }

        return redirect('backend/user')->with('error', 'Có lỗi xảy ra!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = \App\Models\Admin::findOrFail($id);

        $breadcrumb = [
            'title' => $user->title,
            'items' => [
                [
                    'title' => 'Danh sách quản trị',
                    'url' => '/backend/admin'
                ],
                [
                    'title' => 'Sửa thông tin',
                    'url' => route('admin.edit', ['id' => $user])
                ]
            ]
        ];

        return view('backend.admin.show', compact(
            'user',
            'breadcrumb'
        ));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = \App\Models\Admin::findOrFail($id);

        $breadcrumb = [
            'title' => $user->username,
            'items' => [
                [
                    'title' => 'Danh sách quản trị',
                    'url' => '/backend/admin'
                ],
                [
                    'title' => 'Xem chi tiết',
                    'url' => route('admin.show', ['id' => $user])
                ],
            ]
        ];

        return view('backend.admin.edit', compact(
            'user',
            'breadcrumb'
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $__request = $request->all();

        $user = \App\Models\Admin::findOrFail($id);

        
        $user->status = isset($__request["status"]) ? 1 : 0;

        $update = $user->save();

        if ($update) {
            return redirect('backend/user')->with('success', 'Cập nhật thành công');
        }

        return redirect('backend/user')->with('error', 'Có lỗi xảy ra!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = \App\Models\Admin::findOrFail($id);

        if ($user->delete()) {
            session()->flash('success', 'Xóa thành công #' . $id);

            return response()->json([
                'error' => 0,
                'message' => 'Xóa thành công #' . $id,
            ]);
        } else {
            session()->flash('error', 'Không thể xóa#' . $id);

            return response()->json([
                'error' => 1,
                'message' => 'Không thể xóa#' . $id,
            ]);
        }
    }
}

app/Http/Controllers/Backend/Banner.php
<?php

namespace App\Http\Controllers\Backend;

use App\Common\Utility;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Validator;

class Banner extends Base
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $breadcrumb = [
            'title' => 'Danh sách Banner',
            'items' => [
                [
                    'title' => 'Danh sách Banner',
                    'url' => '/backend/banner'
                ]
            ]
        ];

        $banners = \App\Models\Banner::query()->orderBy('order', 'asc')->orderBy('created_time', 'desc')->paginate(24);

        return view('backend.banner.index', compact('banners', 'breadcrumb'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $breadcrumb = [
            'title' => 'Thêm Banner',
            'items' => [
                [
                    'title' => 'Danh sách Banner',
                    'url' => '/backend/banner'
                ],
                [
                    'title' => 'Thêm Banner'
                ]
            ]
        ];

        return view('backend.banner.create', compact(
            'breadcrumb'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $name = $request->get('name', '');
        $description = $request->get('description', '');
        $order = $request->get('order', '');
        $data = [
            'name'=>$name,
            'description'=>$description,
            'order'=>$order,
        ];
        $banner = new \App\Models\Banner($data);
        $update = $banner->save($data);
        if ($update) {
            if (Input::hasFile('image')) {
                $image = Input::file('image');
                $fileName = 'b'.$banner->id.'.jpg';
                $filePath = env('UPLOAD_PATH').'/banner/';
                $url_file_update = env('WEB_PATH').'upload/banner/'.$fileName;

                if(!is_dir($filePath)) {
                    Utility::makeDirectory($filePath);
                }
                $image->move($filePath, $fileName);

                $data_update = [
                    'image_url'=>$url_file_update,
                    'image_name'=>$fileName
                ];
                $banner->update($data_update);
            }

            return redirect()->action('Backend\Banner@index');
        }

        return redirect('backend/banner')->with('error', 'Có lỗi xảy ra!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $banner = \App\Models\Banner::findOrFail($id);

        $breadcrumb = [
            'title' => $banner->name,
            'items' => [
                [
                    'title' => 'Danh sách Banner',
                    'url' => '/backend/banner'
                ],
                [
                    'title' => 'Sửa thông tin',
                    'url' => route('banner.edit', ['id' => $banner])
                ]
            ]
        ];

        return view('backend.banner.show', compact(
            'banner',
            'breadcrumb'
        ));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $banner = \App\Models\Banner::findOrFail($id);

        $breadcrumb = [
            'title' => $banner->title,
            'items' => [
                [
                    'title' => 'Danh sách Banner',
                    'url' => '/backend/banner'
                ],
                [
                    'title' => 'Xem chi tiết',
                    'url' => route('banner.show', ['id' => $banner])
                ],
            ]
        ];

        return view('backend.banner.edit', compact(
            'banner',
            'breadcrumb'
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (Input::hasFile('image')) {
            $image = Input::file('image');

            $file = ['image' => $image];
            $validator = Validator::make($file, [
                'image' => 'mimes:jpeg,bmp,png|max:1000'
            ]);

            if ($validator->fails()) {
                return redirect()->action('Backend\Banner@create')->withInput()->withErrors($validator);
            }
        }

        $banner = \App\Models\Banner::query()->where('id',$id)->first();

        $banner->name = $request->get('name', '');
        $banner->description = $request->get('description', '');
        $banner->order = $request->get('order', 0);

        if ($banner->save()) {
            if (Input::hasFile('image')) {
                $image = Input::file('image');
                $fileName = 'b'.$banner->id.'.jpg';
                $filePath = env('UPLOAD_PATH').'/banner/';
                $url_file_update = env('WEB_PATH').'upload/banner/'.$fileName;

                if(!is_dir($filePath)) {
                    Utility::makeDirectory($filePath);
                }
                $image->move($filePath, $fileName);

                $data_update = [
                    'image_url'=>$url_file_update,
                    'image_name'=>$fileName
                ];
                $banner->update($data_update);
            }

            return redirect()->action('Backend\Banner@show', ['id' => $id]);
        }

        return redirect('backend/banner')->with('error', 'Có lỗi xảy ra!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }

    public function delete($id) {
        $banner =  \App\Models\Banner::query()->where('id',$id)->first();

        $image_path = env('UPLOAD_PATH').'/banner/'.$banner->name;
        if(is_file($image_path)) {
            unlink($image_path);
        }

        $banner->delete();
        return redirect()->action('Backend\Banner@index');
    }
}

app/Http/Controllers/Backend/Base.php
<?php

namespace App\Http\Controllers\Backend;


use App\Http\Controllers\Controller;

class Base extends Controller
{

}

app/Http/Controllers/Backend/Home.php
<?php
namespace App\Http\Controllers\Backend;


class Home extends Base
{
    public function index() {
        
        return view('backend.home.index');
    }
}

app/Http/Controllers/Backend/Image.php
<?php

namespace App\Http\Controllers\Backend;

use App\Common\UploadedImage;
use Illuminate\Http\Request;

class Image extends Base
{
    public function editorUpload(Request $request)
    {
        if ($request->hasFile('file')) {
            $fileName = uniqid();

            $type = $request->get('type', '');

            $uploadedImage = new UploadedImage($request->file('file'));
            $uploadedImage->setFileName($fileName);
            $uploadedImage->setPathDir($type);
            $uploadedImage->move();
            $url = env('WEB_PATH') . 'upload/' . $type . '/' . $fileName . '.jpg';
            echo $url;exit;
        }
        echo '';exit;
    }
}

app/Http/Controllers/Backend/Login.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Admin;

class Login extends Base
{
    
    public function index() {
        return view('backend.login');
    }
    
    public function login()
    {
        $username = request('username','');
        $password = request('password','');
        $exist = Admin::query()
            ->where('username', $username)
            ->where('password',md5($password))->first();
        if(isset($exist) && $exist instanceof Admin) {
            /**@var \Illuminate\Contracts\Auth\Authenticatable $exist*/
            auth()->login($exist);

            return redirect(action('Backend\Home@index'));

        }
        return back()->withErrors('Invalid account!');
    }


    public function logout() {
        auth()->logout();
        return redirect()->to(url('backend/login'));
    }
}

resources/views/backend/banner_sub/create.blade.php
@extends('backend.layout.default')

@section('title', "Thêm video")

@section('style.header')

    @parent
@endsection

@section('content')

    <div class="wrapper wrapper-content">
        <div class="col-lg-10">

            <form method="POST" action="/backend/banner_sub" class="form-horizontal"
                  enctype="multipart/form-data">

                <input name="_method" type="hidden" value="POST" enctype="multipart/form-data">

                {{csrf_field()}}

                <div class="row">
                    <div class="tabs-container">
                        
                        <div class="tab-content">
                            <div id="tab-1" class="tab-pane active">
                                <div class="panel-body">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="name" class="col-sm-2 control-label">Tên</label>

                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" name="name"
                                                       placeholder="name"
                                                       value="">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="name" class="col-sm-2 control-label">Link</label>

                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" name="link"
                                                       placeholder="Link"
                                                       value="">
                                            </div>
                                        </div>


                                        <div class="form-group">
                                            <label for="order" class="col-sm-2 control-label">Sắp xếp</label>

                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="order"
                                                       name="order" placeholder="Sắp xếp"
                                                       value="0">
                                            </div>
                                        </div>


                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">File ảnh</label>

                                            <div class="col-sm-10">
                                                <input type="file" name="image" class="form-control"
                                                       accept="image/*"/>
                                            </div>
                                        </div>

                                        <div class="hr-line-dashed"></div>

                                        <div class="form-group">
                                            <div class="col-sm-2"></div>
                                            <div class="col-sm-10">
                                                <button class="btn btn-primary" type="submit"><i
                                                            class="fa fa-check"></i> Cập nhật
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>

            </form>

        </div>
    </div>

@stop

@section('script.footer')

    @parent
@endsection

resources/views/backend/banner_sub/edit.blade.php
@extends('backend.layout.default')

@section('title', $odm->name)

@section('style.header')

    @parent
@endsection

@section('content')

    <div class="wrapper wrapper-content">
        <div class="col-lg-8">
            <form method="POST" action="/backend/banner_sub/{{$odm->id}}" class="form-horizontal"
                  enctype="multipart/form-data">

                <input name="_method" type="hidden" value="PATCH">

                {{csrf_field()}}

                <div class="row">
                    <div class="tabs-container">
                        @include('backend.element.alert',[])
                        <div class="tab-content">
                            <div id="tab-1" class="tab-pane active">
                                <div class="panel-body">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="name" class="col-sm-2 control-label">Tên video</label>

                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="name" name="name"
                                                       placeholder="Link"
                                                       value="{!! $odm->name !!}">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="name" class="col-sm-2 control-label">Link</label>

                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" name="link"
                                                       placeholder="Link"
                                                       value="{!! $odm->link !!}">
                                            </div>
                                        </div>


                                        <div class="form-group">
                                            <label for="order" class="col-sm-2 control-label">Sắp xếp</label>

                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="order"
                                                       name="order" placeholder="Sắp xếp"
                                                       value="{!! $odm->order !!}">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">File ảnh</label>

                                            <div class="col-sm-10">
                                                <?php
                                                    if(isset($odm) && !empty($odm->image_url)) {
                                                        ?>
                                                        <img src="<?php echo $odm->image_url;?>"
                                                             style="width: 160px;height: 70px;border:1px solid #ccc" />
                                                        <br/>
                                                        <br/>
                                                        <?php
                                                    }
                                                ?>

                                                <input type="file" name="image" class="form-control"
                                                       accept="image/*"/>
                                            </div>
                                        </div>

                                        <div class="hr-line-dashed"></div>

                                        <div class="form-group">
                                            <div class="col-sm-2"></div>
                                            <div class="col-sm-10">
                                                <button class="btn btn-primary" type="submit"><i
                                                            class="fa fa-check"></i> Cập nhật
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>

            </form>
        </div>
    </div>

@stop

resources/views/backend/banner_sub/index.blade.php
@extends('backend.layout.default')

@section('title', "Danh sách Banner")

@section('content')

    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    @include('backend.element.alert',[])
                    <div class="ibox-content">

                        <div class="row">
                            <div class="col-lg-12">
                                <a href="{!! route('banner_sub.create') !!}" class="btn btn-primary"><i
                                            class="fa fa-plus"></i> Thêm</a>
                            </div>
                        </div>

                        @if($datas)
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th class="col-sm-1 text-center">ID</th>
                                    <th class="col-sm-1 text-center">Ảnh</th>
                                    <th>Thông tin chung</th>
                                    <th class="col-sm-1 text-center">Sắp xếp</th>
                                    <th class="col-sm-2 text-center">Thời gian tạo</th>
                                    <th class="col-sm-2 text-center">Hành động</th>

                                </tr>
                                </thead>
                                <tbody>
                                <?php $i = 0;?>
                                @foreach($datas as $tmp)
                                    <tr>
                                        <td class="text-center"><?php $i++;echo $i;?></td>
                                        <td>
                                            <img src="{!! $tmp->image_url !!}" style="width: 120px;height: 60px" />
                                        </td>
                                        <td>
                                            <strong>
                                                <a href="{!! route('banner_sub.edit',['id'=>$tmp->id]) !!}">
                                                    {{$tmp->name}}
                                                </a>
                                            </strong>
                                        </td>
                                        <td class="text-center">{{$tmp->order}}</td>
                                        <td class="text-center">
                                            {{ \App\Common\Utility::displayDatetime($tmp->created_time) }}
                                        </td>
                                        <td width="150" class="text-center">

                                            <a class="btn btn-warning btn-xs m-l-3"
                                               href="{!! route('banner_sub.edit',['id'=>$tmp->id]) !!}"
                                               title="Sửa">
                                                <i class="fa fa-pencil"></i> Sửa
                                            </a>

                                            <a class="btn btn-danger btn-xs m-l-3 delete_item"
                                               href="{!! url('backend/banner_sub/delete',['id'=>$tmp->id]) !!}"
                                               title="Xóa">
                                                <i class="fa fa-trash"></i> Xóa
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>

                            {!! $datas->render() !!}

                        @endif

                    </div>
                </div>
            </div>
        </div>
    </div>

@stop